[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "stat_properties: marks tests to avoid running tests based on statistical properties that can fail somtimes.",
]
