SimulationDir       ./obs_files
SimulationLabel     test_base
NumberOfSimulations 2
NumberOfPoints      6556
SamplingPeriod      1.0
RepeatableNoise     True
MissingData         False
PercMissingData     0.0
Trend               0.0
NominalBias         0.0
NoiseModels         Matern
